version: '3.8'
name: consul-and-vault

services:
  vault:
    container_name: vault
    image: docker.io/hashicorp/vault:latest
    ports:
      - 8200:8200
    volumes:
      - ./vault/config:/c/Users/kusan/Documents/data/vault/config
      - ./vault/policies:/c/Users/kusan/Documents/data/vault/policies
      - ./vault/data:/c/Users/kusan/Documents/data/vault/data
      - ./vault/logs:/c/Users/kusan/Documents/data/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: server -config=/c/Users/kusan/Documents/data/vault/config/config.json
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul
  consul:
    container_name: consul
    image: docker.io/hashicorp/consul:latest
    ports:
      - 8500:8500
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=/c/Users/kusan/Documents/data/consul/config/config.json
    volumes:
      - ./consul/config/consul-config.json:/c/Users/kusan/Documents/data/consul/config/config.json
      - ./consul/data:/c/Users/kusan/Documents/data/consul/data
