version: '3.8'
name: mongodb-and-postgres

services:
  postgres:
    image: postgres:16.1
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/c/Users/kusan/Documents/data/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017
    volumes:
      - "dbdata6:/c/Users/kusan/Documents/data/mongodb"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
volumes:
  dbdata6: