version: '3.8'
name: kafka-and-zookeper

services:
    # https://hub.docker.com/r/confluentinc/cp-zookeeper
    zookeeper:
        image: 'confluentinc/cp-zookeeper:7.5.0'
        container_name: zookeeper-7.5.0
        ports:
            - '2181:2181'
        volumes:
            - 'zookeeper_data:/c/Users/kusan/Documents/data/kafka/zookeper'
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        healthcheck:
            test: ["CMD", "nc", "-z", "localhost", "2181"]
            interval: 10s
            timeout: 5s
            retries: 5
        deploy:
          resources:
            reservations:
              cpus: '0.2'
              memory: 256M
            limits:
              cpus: '0.4'
              memory: 512M

    #https://hub.docker.com/r/confluentinc/cp-kafka
    kafka:
        image: 'confluentinc/cp-kafka:7.5.0'
        container_name: kafka-7.5.0
        ports:
            - '9092:9092'
        volumes:
            - 'kafka_data:/c/Users/kusan/Documents/data/kafka'
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        depends_on:
            zookeeper:
                condition: service_healthy
        deploy:
          resources:
            reservations:
              cpus: '1'
              memory: 512M
            limits:
              cpus: '2'
              memory: 1024M
            
volumes:
    zookeeper_data:
        driver: local
    kafka_data:
        driver: local
