version: '3.8'
name: cache

services:
  redis-cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis-cache:/data
  memcached:  
    image: memcached:1.6.18
    restart: always
    ports:  
      - '11211:11211' 
    volumes: 
      - memcached:/data
volumes:
  redis-cache:
    driver: local
  memcached:
    driver: local