version: '3.8'
name: pgadmin4

services:
 pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: me@kusandriadi.com    # Set to "admin"
      PGADMIN_DEFAULT_PASSWORD: admin # Set to "admin"
    ports:
      - "8181:80"
    volumes:
      - /c/Users/kusan/Documents/data/pgadmin:/var/lib/pgadmin
    deploy:
      resources:
        reservations:
          cpus: '0.2'
          memory: 256M
        limits:
          cpus: '0.4'
          memory: 512M