version: '3.8'
name: cache

services:
  redis-cache:
    container_name: redis-6.2
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - /c/Users/kusan/Documents/data/cache/redis:/data
    deploy:
      resources:
        reservations:
          cpus: '0.4'
          memory: 32M
        limits:
          cpus: '0.8'
          memory: 64M
  memcached:
    container_name: memcached-1.6.18
    image: memcached:1.6.18
    restart: always
    ports:
      - '11211:11211'
    deploy:
      resources:
        reservations:
          cpus: '0.4'
          memory: 32M
        limits:
          cpus: '0.8'
          memory: 64M