version: '3.8'
name: mongodb-and-postgres

services:
  postgres:
    container_name: postgres-16.1
    image: postgres:16.1
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 128M
        limits:
          cpus: '1'
          memory: 256M

  mongodb:
    container_name: mongodb-6.0
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      MONGODB_INITDB_ROOT_USERNAME: mongo
      MONGODB_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    deploy:
      resources:
        reservations:
          cpus: '1'
          memory: 256M
        limits:
          cpus: '2'
          memory: 512M

volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local