version: '3.8'
name: kafka-and-zookeper

services:
    # https://hub.docker.com/r/bitnami/zookeeper
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        container_name: zookeeper-local
        ports:
            - '2181:2181'
        volumes:
            - 'zookeeper_data:/c/Users/kusan/Documents/data/kafka'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
              
    #https://hub.docker.com/r/bitnami/kafka
    kafka:
        image: 'bitnami/kafka:latest'
        container_name: kafka-local
        ports:
            - '9092:9092'
        volumes:
            - 'kafka_data:/d/docker/kafka'
        environment:
            - 'ALLOW_PLAINTEXT_LISTENER=yes'
            - 'KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181'
            - 'KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT'
            - 'KAFKA_CFG_LISTENERS=INSIDE://:9092'
            - 'KAFKA_CFG_ADVERTISED_LISTENERS=INSIDE://localhost:9092'
            - 'KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INSIDE'
        depends_on:
            - zookeeper 
            
volumes:
    zookeeper_data:
        driver: local
    kafka_data:
        driver: local
