version: '3.8'
name: consul-and-vault

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - 8200:8200
    volumes:
      - 'vault_config:/d/docker/vault/config'
      - 'vault_policies:/d/docker/vault/policies'
      - 'vault_data:/d/docker/vault/data'
      - 'vault_log:/d/docker/vault/logs'
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: server -config=/d/docker/vault-config.json
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - 8500:8500
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=consul-config.json
    volumes:
      - 'consul_config:/d/docker/consul-config.json'
      - 'consul_data:/d/docker/vault/data'
volumes:
    vault_config:
        driver: local
    vault_policies:
        driver: local
    vault_data:
        driver: local
    vault_log:
        driver: local
    consul_config:
        driver: local
    consul_data:
        driver: local